# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for elasticsearch
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

conf:
  elasticsearch:
    override:
    prefix:
    append:
    bootstrap:
      memory_lock: true
    cluster:
      name: elasticsearch
    network:
      host: 0.0.0.0
    path:
      data: /var/lib/elasticsearch/data
      # TODO(srwilkers): Update this log path with meaningful config overrides
      logs: /var/lib/elasticsearch/data
    zen:
      min_masters: 2
    env:
      java_opts: "-Xms256m -Xmx256m"
  logging:
    override:
    prefix:
    append:

endpoints:
  logging_db:
    name: elasticsearch
    hosts:
      data: elasticsearch-data
      default: elasticsearch-logging
      discovery: elasticsearch-discovery
      public: elasticsearch
    path:
      default: null
    scheme:
      default: http
    port:
      api:
        default: 9200

images:
  memory_init: docker.io/kolla/ubuntu-source-elasticsearch:4.0.0
  elasticsearch: docker.io/kolla/ubuntu-source-elasticsearch:4.0.0
  helm_tests: docker.io/kolla/ubuntu-source-elasticsearch:4.0.0
  pull_policy: "IfNotPresent"

pod:
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  replicas:
    master: 3
    data: 3
    client: 2
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
    termination_grace_period:
      master:
        timeout: 600
      data:
        timeout: 600
      client:
        timeout: 600
  resources:
    enabled: false
    client:
      limits:
        memory: "1024Mi"
        cpu: "2000m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    master:
      limits:
        memory: "1024Mi"
        cpu: "2000m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    data:
      limits:
        memory: "1024Mi"
        cpu: "2000m"
      requests:
        memory: "128Mi"
        cpu: "500m"

network:
  client:
    port: 9200
    node_port:
      enabled: false
      port: 30920
  discovery:
    port: 9300
    node_port:
      enabled: false
      port: 30930
  data:
    port: 9300
    node_port:
      enabled: false
      port: 30931

pvc:
  name: pvc-elastic
  requests:
    storage: 2Gi
  storage_class: general
