# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for artifactory.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

labels:
  server:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

release_group: null

images:
  tags:
    db_init: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
    db_drop: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    artifactory: quay.io/attcomdev/artifactory-pro-mysql:5.9.3
    image_repo_sync: docker.io/docker:17.07.0
  pull_policy: "IfNotPresent"
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

network:
  node_ports:
    enabled: false
  http:
    port: 8081
    node_port: 31672
  docker:
    port: 5050
    node_port: 31777
  secure:
    port: 5052
    node_port: 31776

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - artifactory-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    server:
      services:
        - endpoint: internal
          service: oslo_cache
        - endpoint: internal
          service: oslo_db
    db_drop:
      services:
        - endpoint: internal
          service: oslo_db
    db_init:
      services:
        - endpoint: internal
          service: oslo_db

storage: pvc

volume:
  size: 100Gi
  class_name: general

chown_on_start: true

pod:
  resources:
    enabled: false
    jobs:
      db_init:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      db_drop:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
  lifecycle:
    upgrades:
      deployments:
        pod_replacement_strategy: RollingUpdate
        revision_history: 1
        rolling_update:
          max_surge: 1
          max_unavailable: 1

secrets:
  oslo_db:
    admin: artifactory-db-admin
    artifactory: artifactory-db-user

# typically overridden by environmental values, but should include all
# endpoints required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  oslo_db:
    namespace: null
    auth:
      admin:
        username: root
        password: password
      artifactory:
        username: artifactory
        password: password
    hosts:
      default: mariadb
    host_fqdn_override:
      default: null
    path: /artifactory
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
  cicd:
    name: artifactory
    hosts:
      default: artifactory

manifests:
  configmap_bin: true
  configmap_etc: true
  statefulset: true
  job_image_repo_sync: true
  job_db_init: true
  job_db_drop: false
  secret_db: true
  secret_db_creds: true
  pvc_artifactory: true
  service: true

# bootstrap/seed artifactory configuration
bootstrap:
  master_key: null
