apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fullname" . }}-preload"
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  preload.yml: |
{{ toYaml .Values.mysql_users_init.preload | indent 4 }}
